config:
  aws:region: us-east-1
  discord-letterboxd-hook:parameterName: "/letterboxd/lastSeenId"
  discord-letterboxd-hook:memorySize: "128"
  discord-letterboxd-hook:timeoutSeconds: "10"
  discord-letterboxd-hook:scheduleExpression: "rate(30 minutes)"
  discord-letterboxd-hook:scheduleName: "letterboxd-every-30m"
  discord-letterboxd-hook:discordWebhookUrl:
    secure: v1:6W3fV+QcKSYEsDhp:sEcqAVqV8hzxCosIqxWJUldF71NtOmUiziLLeSM57T+waMgtVGGs2520/NYiVmNmbubA6RKLnO1NgparcIIix1ohys09KzAp1EFW/5nYPQ4Fwt8n3yP0/sfdTFgwgUgCcuumRm/nsmDI9R585iYceMjc8o2GC2eDcHw4u+VXChOfeQZCeSU14oM=
  discord-letterboxd-hook:logLevel: "info"
  discord-letterboxd-hook:enableSchedule: "true"
  discord-letterboxd-hook:scheduleForceMostRecent: "false"
  aws:accessKey:
    secure: v1:Xabutpgqoqg42aOb:J+xm7bxoG616lvPYFvtT8JOZrJcHZtNF07a1472c3N8/Wshd
  aws:secretKey:
    secure: v1:Zj0C5DAgzsBS7C3T:cavXWefZ2CTmZH6UZqqlel+bcDkjQ+Zt3THInczOPA83O7s9QQ+FwQB3hHb8suv0PR3ZvNhR+dw=
  discord-letterboxd-hook:username:
    secure: v1:t8mrJOcUtcc4KqoJ:P1CQmgYI+de+s1b2rOKDl1kgBb3dCDdhmfM0eynnwt6E5f3s2DwDSg==
encryptionsalt: v1:idfmFUm4WR8=:v1:d23QgKqbe5PAfbFW:VEaG/uZvozuo/rvyTrBfGpoYw3xg6A==
