config:
  aws:region: us-east-1
  aws:accessKey: YOUR_AWS_KEY
  aws:secretKey: YOUR_AWS_SECRET
  discord-letterboxd-hook:username: YOUR_DISCORD_USERNAME
  discord-letterboxd-hook:parameterName: "/letterboxd/lastSeenId"
  discord-letterboxd-hook:memorySize: "128"
  discord-letterboxd-hook:timeoutSeconds: "10"
  discord-letterboxd-hook:scheduleExpression: "rate(30 minutes)"
  discord-letterboxd-hook:scheduleName: "letterboxd-every-30m"
  discord-letterboxd-hook:discordWebhookUrl: https://discord.com/api/webhooks/...
  discord-letterboxd-hook:logLevel: "info"
  discord-letterboxd-hook:enableSchedule: "true"
  discord-letterboxd-hook:scheduleForceMostRecent: "false"
