config:
  gcp:project: your-gcp-project-id
  discord-letterboxd-hook-gcp:location: us-central1
  discord-letterboxd-hook-gcp:username: YOUR_USERNAME_HERE
  discord-letterboxd-hook-gcp:discordWebhookUrl: https://discord.com/api/webhooks/...
  discord-letterboxd-hook-gcp:scheduleExpression: "*/30 * * * *"
  discord-letterboxd-hook-gcp:timeZone: Etc/UTC
  discord-letterboxd-hook-gcp:logLevel: info
  discord-letterboxd-hook-gcp:persistForcedState: "true"
  discord-letterboxd-hook-gcp:stateObject: lastSeenId
  discord-letterboxd-hook-gcp:maxPosts: "1"
