config:
  azure-native:location: eastus
  azure-native:subscriptionId: YOUR_AZURE_SUBSCRIPTION_ID
  azure-native:tenantId: YOUR_AZURE_TENANT_ID
  azure-native:clientId: YOUR_AZURE_APP_ID
  azure-native:clientSecret: YOUR_AZURE_APP_SECRET
  discord-letterboxd-hook-azure:username: YOUR_LETTERBOXD_USERNAME
  discord-letterboxd-hook-azure:discordWebhookUrl: https://discord.com/api/webhooks/...
  discord-letterboxd-hook-azure:scheduleExpression: "0 */30 * * * *"
  discord-letterboxd-hook-azure:logLevel: info
  discord-letterboxd-hook-azure:persistForcedState: "true"
  discord-letterboxd-hook-azure:stateContainer: letterboxd-state
  discord-letterboxd-hook-azure:codeContainer: function-code
